var a=0,b=0,c=0,d=10,e=!1,f=!1,g=!1,h=!1,i=!1,actualCell=0,actualX=0,actualY=0,cellsPerRow=64,rows=66,playerSpeed=0.1,playerX=4,playerY=1,targetPX=4,targetPY=1,playerScreenPadX=0,playerScreenPadY=0,cellReplaceX=0,cellReplaceY=0,collisionPlayerOnCell=0,collisionCellUp=0,collisionCellDown=0,collisionCellLeft=0,collisionCellRight=0,canGoToUp=!0,canGoToDown=!0,canGoToLeft=!0,canGoToRight=!0,tilesetTileSize=32,tilesetTilesOnWidth=
16,tilesetTileOnX=0,tilesetTileOnY=0,tilesetX=0,tilesetY=0,tilesetToUse=1,playerAnimationSpeed=0.1,playerAnimSpeedEq=0,playerTileset="ressource/tilesets/player.png",playerTileX=0,playerTileY=0,playerAnimationWidth=2,playerTileSize=32,playerTileFrameX=0,playerTileFrameY=0,tileset1="ressource/tilesets/dustvg.png",tileset2="",colCellUp=0,colCEllDown=0,colCellLeft=0,colCellRight=0,colCurrentRow=0,colPlayerX=0,colPlayerY=0,cellSizeZoom=50,collisionBuffer=5,colBufPercent=0.05,cellsToDrawAroundPlayer=9,
screen_width=800,screen_height=600,c=document.getElementById("myCanvas"),ctx=null;function InitiateMeligineCore(){document.addEventListener("keydown",keyDown,!1);document.addEventListener("keyup",keyUp,!1);e=!1;c=document.getElementById("myCanvas");ctx=c.getContext("2d");MeligineInitiateObjects();setInterval(function(){MeligineCore()},1)}function MeligineInitiateObjects(){}
function keyDown(a){39==a.keyCode?f=!0:37==a.keyCode&&(g=!0);38==a.keyCode?h=!0:40==a.keyCode&&(i=!0)}function keyUp(a){39==a.keyCode?f=!1:37==a.keyCode&&(g=!1);38==a.keyCode?h=!1:40==a.keyCode&&(i=!1)}function mouseOvere(){e?e=!1:!1==e&&(e=!0)}function moreCells(){20<cellsToDrawAroundPlayer||cellsToDrawAroundPlayer++}function lessCells(){1>cellsToDrawAroundPlayer||cellsToDrawAroundPlayer--}
function zoomIn(){200<cellSizeZoom||(cellSizeZoom+=5)}function zoomOut(){10>cellSizeZoom||(cellSizeZoom-=5)}function MeligineCore(){UpdateValues();CollisionCaculate();0==b?MeligineSplashRender():2==b&&MeligineGameScreenRender();MeligineFPSCounter()}function MeligineFPSCounter(){var a=(new Date).getMilliseconds(),b=Math.round(1E3/(a-a));a=a;ctx.fillStyle="rgb(0,255,0)";ctx.fillText("FPS : "+b,700,16)}
function UpdateValues(){g?canGoToLeft&&(playerX-=playerSpeed,playerAnimSpeedEq+=playerAnimationSpeed,playerTileY=1):f&&canGoToRight&&(playerX+=playerSpeed,playerAnimSpeedEq+=playerAnimationSpeed,playerTileY=2);h?canGoToUp&&(playerY-=playerSpeed,playerAnimSpeedEq+=playerAnimationSpeed,playerTileY=3):i&&canGoToDown&&(playerY+=playerSpeed,playerAnimSpeedEq+=playerAnimationSpeed,playerTileY=0);playerAnimSpeedEq>=playerAnimationWidth&&(playerAnimSpeedEq=0);playerTileX=Math.round(playerAnimSpeedEq);
playerTileFrameX=playerTileX*playerTileSize;playerTileFrameY=playerTileY*playerTileSize;playerScreenPadX=screen_width-screen_width/2-playerX*cellSizeZoom;playerScreenPadY=screen_height-screen_height/2-playerY*cellSizeZoom;collisionBuffer=colBufPercent*cellSizeZoom}
function CollisionCaculate(){collisionPlayerOnCell=Math.round(playerY)*cellsPerRow+Math.round(playerX);collisionCellUp=collisionPlayerOnCell-cellsPerRow;collisionCellDown=collisionPlayerOnCell+cellsPerRow;collisionCellLeft=collisionPlayerOnCell-1;collisionCellRight=collisionPlayerOnCell+1;colCurrentRow=Math.round(playerY)*cellsPerRow;colCellUp=(1+Math.floor(collisionCellUp/cellsPerRow))*cellSizeZoom;colCellDown=(Math.floor(collisionCellDown/cellsPerRow)-1)*cellSizeZoom;colCellLeft=(1+Math.floor(collisionCellLeft-
colCurrentRow))*cellSizeZoom;colCellRight=(Math.floor(collisionCellRight-colCurrentRow)-1)*cellSizeZoom;colPlayerX=playerX*cellSizeZoom;colPlayerY=playerY*cellSizeZoom;1==allCollisionCells[collisionCellUp]?canGoToUp=colPlayerY-collisionBuffer<colCellUp+collisionBuffer?!1:!0:0==allCollisionCells[collisionCellUp]&&(canGoToUp=!0);1==allCollisionCells[collisionCellDown]?canGoToDown=colPlayerY+collisionBuffer>colCellDown-collisionBuffer?!1:!0:0==allCollisionCells[collisionCellDown]&&(canGoToDown=!0);1==
allCollisionCells[collisionCellLeft]?canGoToLeft=colPlayerX-collisionBuffer<colCellLeft+collisionBuffer?!1:!0:0==allCollisionCells[collisionCellLeft]&&(canGoToLeft=!0);1==allCollisionCells[collisionCellRight]?canGoToRight=colPlayerX+collisionBuffer>colCellRight-collisionBuffer?!1:!0:0==allCollisionCells[collisionCellRight]&&(canGoToRight=!0)}function MeligineSplashRender(){c==d&&(c=0,b=2);c++;MeligineCleanTheScreen();MeligineSplashScreen()}
function MeligineGameScreenRender(){MeligineCleanTheScreen();for(var a=actualCell=0;a<rows;a++)if(actualY=a,actualY>playerY-cellsToDrawAroundPlayer+2&&actualY<playerY+cellsToDrawAroundPlayer-2)for(var b=0;b<cellsPerRow;b++){actualX=b;if(actualX>playerX-cellsToDrawAroundPlayer&&actualX<playerX+cellsToDrawAroundPlayer){var d=new Image;1==tilesetToUse&&(d.src=tileset1);cellReplaceX=playerScreenPadX+actualX*cellSizeZoom-cellSizeZoom/2;cellReplaceY=playerScreenPadY+actualY*cellSizeZoom-cellSizeZoom/2;
tilesetTileOnY=Math.floor(allCells[actualCell]/tilesetTilesOnWidth);tilesetTileOnX=allCells[actualCell]-tilesetTileOnY*tilesetTilesOnWidth;tilesetX=tilesetTileOnX*tilesetTileSize;tilesetY=tilesetTileOnY*tilesetTileSize;ctx.drawImage(d,tilesetX,tilesetY,tilesetTileSize,tilesetTileSize,cellReplaceX,cellReplaceY,cellSizeZoom,cellSizeZoom);ctx.fillStyle="rgb(255,0,255)"}actualCell++}else actualCell+=cellsPerRow;MeligineDrawThePlayer()}
function MeligineSplashScreen(){var a=new Image;a.src="ressource/logos/splash.png";ctx.drawImage(a,0,0)}function MeligineDrawThePlayer(){var a=new Image;a.src=playerTileset;ctx.drawImage(a,playerTileFrameX,playerTileFrameY,playerTileSize,playerTileSize,400-cellSizeZoom/2,300-cellSizeZoom/2,cellSizeZoom,cellSizeZoom);ctx.fillStyle="rgb(0,255,0)"}function MeligineCleanTheScreen(){ctx.fillStyle="rgb(0,0,0)";ctx.fillRect(0,0,screen_width,screen_height)};